#
# enable and configure selinux
#

- name: Install Fedora dnf-utils & selinux python3 Packages
  ansible.builtin.package:
    name: dnf-utils, libselinux-python3, libsemanage-python3
    state: latest
  when:
    - ansible_distribution == "Fedora" 

- name: Install RHEL selinux python3 Packages
  ansible.builtin.package:
    name: libselinux-python3, libsemanage-python3
    state: latest
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version >= "8"

- name: enable selinux
  ansible.builtin.selinux:
    policy: targeted
    state: enforcing
  when:
    - ansible_os_family == "RedHat"

...
