---
#
# Configure gatekeeper with openwrt
#
# To do before running this playbook:
#
# set root password vi luci interface
# user@localhost> ssh-copy-id <ssh-key>.pub root@openwrt
# root@openwrt> opkg update
# root@openwrt> opkg install python3 openssh-sftp-server
#

- name: configure gatekeeper with openwrt
  hosts: gatekeeper
  become: yes

  tasks:
    - name: include secrets.yml
      include_vars:
        file: vars/secrets.yml

    - name: configure luci for SSL
      community.general.opkg:
        name: luci-ssl
        state: present
        update_cache: yes
      notify: restart luci

    - name: install /etc/config/system template
      ansible.builtin.template:
        src: etc.config.system.j2
        dest: /etc/config/system
        owner: root
        group: root
        mode: 0644
      notify: restart system

    - name: install /etc/config/network template
      ansible.builtin.template:
        src: etc.config.network.j2
        dest: /etc/config/network
        owner: root
        group: root
        mode: 0644
      notify: restart network

    - name: install dnsmasq.conf file
      ansible.builtin.template:
        src: etc.dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        owner: root
        group: dnsmasq
        mode: 0644
      notify: restart dnsmasq

    - name: modify dhcp config
      ansible.builtin.template:
        src: etc.config.dhcp.j2
        dest: /etc/config/dhcp
        owner: root
        group: root
        mode: 0644
      notify: restart dhcp

    - name: install /etc/config/wireless template
      ansible.builtin.template:
        src: etc.config.wireless.j2
        dest: /etc/config/wireless
        owner: root
        group: root
        mode: 0644
      notify: restart wireless

    - name: install ddns packages for {{service_name}}
      community.general.opkg:
        name: "{{ item }}"
        state: present
        update_cache: yes
      notify: restart ddns
      with_items:
        - ddns-scripts
        - wget
        - ca-certificates
        - curl
        - ca-bundle
        - ddns-scripts_no-ip_com
        - luci-app-ddns
#      notify: restart luci

    - name: install /etc/config/ddns template
      ansible.builtin.template:
        src: etc.config.ddns.j2
        dest: /etc/config/ddns
        owner: root
        group: root
        mode: 0644
      notify: restart ddns

    - name: install /etc/config/firewall template
      ansible.builtin.template:
        src: etc.config.firewall.j2
        dest: /etc/config/firewall
        owner: root
        group: root
        mode: 0644
      notify: restart firewall

    - name: install /etc/hosts file
      ansible.builtin.copy:
        src: "etc.hosts"
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
      notify: restart dnsmasq

  handlers:
    - name: restart system
      ansible.builtin.service:
        name: system
        state: restarted
        enabled: yes

    - name: restart network
      ansible.builtin.service:
        name: network
        state: reloaded
        enabled: yes

    - name: restart wireless
      ansible.builtin.command: wifi reload

    - name: restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
        enabled: yes

    - name: restart dhcp # provided by dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
        enabled: yes

    - name: restart ddns
      ansible.builtin.service:
        name: ddns
        state: restarted
        enabled: yes

    - name: restart firewall
      ansible.builtin.service:
        name: firewall
        state: restarted
        enabled: yes

    - name: restart luci
      ansible.builtin.command: reboot -f
...

