---
- name: Provision AWS Tower Instance
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/all
  - host_vars/tower-aws

  roles:
  - aws_create_vpc

  tasks:
  - name: Launch AWS Tower Instance
    ec2:
      #access_key: "{{ ec2_access_key }}"
      #secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ my_security_group.group_name }}"
      group_id: "{{ my_security_group.group_id }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      vpc_subnet_id: "{{ my_vpc_subnet.subnet.id }}"
      instance_tags:
        Name: "{{ tower_user_name }}_tower"
        ansible_group: "{{ ec2_ansible_group }}"
        AlwaysUp: "{{ critical_vm }}"
        Contact: "{{ my_email_address }}"
        DeleteBy: Never
      count: 1
      termination_protection: yes
      wait: true
    register: ec2

  - name: Wait for SSH connection to Tower Instance
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22 
      delay: 60 
      timeout: 320 
      state: started
    with_items: "{{ ec2.instances }}"
...
