---
- name: Provision AWS Tower Instance
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/all
  - host_vars/tower-aws

  tasks:
  - name: Launch AWS Tower Instance
    ec2:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      instance_tags: "{'ansible_group':'tower', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'{{ tower_user_name }}''-tower'}"
      count: 1
      wait: true
    register: ec2

  - name: Wait for SSH connection to Tower Instance
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22 
      delay: 60 
      timeout: 320 
      state: started
    with_items: "{{ ec2.instances }}"
...
