---
#
# Configure eagle workstation
#

# CentOS 8 Prerequisites: 
#	python3
#	policycoreutils-python3
#	rsync

- hosts: eagle
  become: yes

  roles:
    - role: config-local-repos
      tags: ['config-local-repos']

    - role: disable-ipv6
      tags: ['disable-ipv6']

    - role: selinux
      tags: ['selinux']

    - role: ssh-config
      tags: ['ssh-config']

    - role: shell-env #including both ssh-keys on server and p51s ??
      tags: ['shell-env']

    - role: set-default-editor
      tags: ['set-default-editor']

    - role: apply-updates
      tags: ['apply-updates']

    - role: virtio-win-local-repo
      tags: ['virtio-win-local-repo']

    - role: setup-epel
      tags: ['setup-epel']

    - role: fail2ban
      tags: ['fail2ban']

## DON'T AUTO REBOOT IF RUNNING KVM VMs
## At least not until the role is modified to accomodate it
#    - role: reboot-if-required
#      tags: ['reboot-if-required']


  tasks:
    - name: configure system to keep only 2 most recent kernels
      ansible.builtin.replace:
        path: /etc/dnf/dnf.conf
        regexp: '^installonly_limit=.+\n'
        replace: 'installonly_limit="{{installed_kernel_limit}}"\n'
        owner: root
        group: root
        mode: '0644'

    - name: install other packages 
      ansible.builtin.package:
        name: nmap, lftp, ftp, openscap, openscap-scanner, openscap-utils, openscap-python3, python3-botocore, python3-boto3, python3-pyvmomi, ansible, screen, virtio-win
        state: latest
      tags:
        - localpkgs

    - name: install other fedora packages 
      ansible.builtin.package:
        name: openscap-containers, openscap-daemon, python3-boto, openwsman-winrs.x86_64, vnstat, nmon
        state: latest
      when: 
        - ansible_distribution == "Fedora"
      tags:
        - localpkgs

    - name: start and enable vnstat
      ansible.builtin.service:
        name: vnstat
        state: started
        enabled: yes
