---
#
# Configure Server0
#

- hosts: ks-server
  become: yes

  roles:
    - role: sm-register
      tags: ['sm-register']

    - role: selinux
      tags: ['selinux']

    - role: http-repo
      tags: ['http-repo']

    - role: config-local-repos
      tags: ['config-local-repos']

    - role: apply-updates
      tags: ['apply-updates']

    - role: tftp-server
      tags: ['tftp-server']

    - role: ssh-config
      tags: ['ssh-config']

    - role: shell-env #including both ssh-keys on server and p51s ??
      tags: ['shell-env']

    - role: kickstart
      tags: ['kickstart']

    - role: ddns
      tags: ['ddns']

    # use the insights register role from galaxy.ansible.com
    - role: RedHatInsights.insights-client
      tags: ['insights']
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version > "5"

    - role: reboot-if-required
      tags: ['reboot-if-required']

