---
#
# Configure kvmhost
#

# CentOS 8 Prerequisites: 
#	python3
#	policycoreutils-python3
#	rsync

- hosts: kvmhost
  become: yes

  roles:
    - role: selinux
      tags: ['selinux']

#    - role: config-local-repos
#      tags: ['config-local-repos']

    - role: apply-updates
      tags: ['apply-updates']

    - role: ssh-config
      tags: ['ssh-config']

    - role: shell-env
      tags: ['shell-env']

    - role: setup-epel
      tags: ['setup-epel']

#    - role: fail2ban
#      tags: ['fail2ban']

#    - role: syslog
#      tags: ['syslog']

    - role: setup-br0
      tags: ['setup-br0']

#    - role: virt-server
#      tags: ['virt-server']

#    - role: backup
#      tags: ['backup']

    # use the insights register role from galaxy.ansible.com
#    - role: RedHatInsights.insights-client
#        vars:
#          insights_display_name: 'kvmhost'
#      when:
#        - ansible_distribution == "RedHat"
#        - ansible_distribution_major_version > "5"
#      tags: ['insights']
#
    - role: reboot-if-required
      tags: ['reboot-if-required']

