---
#
# Configure p51s
#

- hosts: p51s
  connection: local
  become: yes

  roles:
    - role: setup-azure
      tags: ['setup-azure']

    - role: setup-vscode
      tags: ['setup-vscode']

    - role: config-local-repos
      tags: ['config-local-repos']

    - role: apply-updates
      tags: ['apply-updates']

    - role: time-server
      tags: ['time-server']

    - role: ssh-config
      tags: ['ssh-config']

    - role: syncscripts
      tags: ['syncscripts']

    - role: dnsmasq
      tags: ['dnsmasq']

    - role: http-repo
      tags: ['http-repo']

    - role: kickstart
      tags: ['kickstart']

    - role: samba-server
      tags: ['samba-server']

    - role: virt-server
      tags: ['virt-server']

    - role: nfs-server
      tags: ['nfs-server']

    - role: yubikey-customize
      tags: ['yubikey-customize']

#    - role: fail2ban
#      tags: ['fail2ban']

#    - role: postfix
#      tags: ['postfix']

#    - role: syslog
#      tags: ['syslog']

#    - role: backup
#      tags: ['selinux']

    - role: selinux
      tags: ['selinux']

#    - role: reboot-if-required
#      tags: ['reboot-if-required']

  tasks:
    - name: set hostname
      hostname:
        name: "{{ansible_hostname}}.{{domain_name}}"

    - name: unmount /run/media/chris/Archive
      mount:
        path: /run/media/chris/Archive
        fstype: ext4
        state: unmounted

    - name: configure fstab to mount /export/archive and mount it
      mount:
        path: /export/archive
        src: LABEL=Archive
        fstype: ext4
        state: mounted

    - name: disable Wayland
      copy:
        src: files/gdm.custom.conf
        dest: /etc/gdm/custom.conf
        owner: root
        group: root
        mode: 0644
    
    - name: install bluejeans
      package:
        name: /export/archive/Linux/RPMS/bluejeans-1.37.22.x86_64.rpm
        state: present

    - name: install adobe flashplayer repo
      package:
        name: /export/archive/Linux/RPMS/adobe-release-x86_64-1.0-1.noarch.rpm
        state: present

    - name: install flashplugin
      package:
        name: flash-plugin
        state: latest

    - name: install zoom
      package:
        name: /export/archive/Linux/RPMS/zoom_x86_64.rpm
        state: present

    - name: install skype
      package:
        name: /export/archive/Linux/RPMS/skypeforlinux-64.rpm
        state: present

    - name: install awscli
      package:
        name: awscli, python2-boto, python2-boto3, python3-boto, python3-boto3, python3-botocore 
        state: latest

    - name: install pyvmomi
      package:
        name: python2-pyvmomi, python3-pyvmomi
        state: latest

    - name: import atom gpg key
      rpm_key:
        state: present
        key: https://packagecloud.io/AtomEditor/atom/gpgkey

    - name: setup atom repo
      yum_repository:
        name: Atom
        description: "Atom Editor"
        file: /etc/yum.repos.d/atom
        baseurl: https://packagecloud.io/AtomEditor/atom/el/7/$basearch
        enabled: yes
        metadata_expire: 1d
        repo_gpgcheck: 0
        #type: rpm
        gpgcheck: yes
        gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
        skip_if_unavailable: true
        keepcache: false

    - name: install atom
      package:
        name: atom
        state: latest

#    - name: import rhel7-csb gpg key
#      rpm_key:
#        state: present
#        key: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-helpdesk-new

    - name: setup rhel7-csb repo
      yum_repository:
        name: rhel7-csb
        description: "RHEL7 CSB Packages"
        file: /etc/yum.repos.d/rhel7-csb
        baseurl: http://hdn.corp.redhat.com/rhel7-csb-stage
        enabled: no
        metadata_expire: 1d
        repo_gpgcheck: 0
        #type: rpm
        gpgcheck: yes
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-helpdesk-new
        skip_if_unavailable: true
        keepcache: false

    - name: install RedHat VPN
      yum:
        name: redhat-internal-NetworkManager-openvpn-profiles, redhat-internal-cert-install
        state: latest
        enablerepo: rhel7-csb
    
    - name: install slack
      package:
        name: /export/archive/Linux/RPMS/slack-3.3.3-0.1.fc21.x86_64.rpm
        state: present
    
    - name: check if /usr/lib/slack/libnode.so.old exists
      stat:
        path: /usr/lib/slack/libnode.so.old
      register: libnode

    - name: setup slack
      block:
    
        - name: copy file fix broken slack libnode.so on fedora
          copy: 
            remote_src: true
            src: /usr/lib/slack/libnode.so
            dest: /usr/lib/slack/libnode.so.old
            owner: root
            group: root
            mode: 0755

        - name: copy file fix broken slack libnode.so on fedora
          file: 
            path: /usr/lib/slack/libnode.so
            state: absent

        - name: make link to fix broken slack libnode.so on fedora
          file: 
            src: /usr/share/atom/libnode.so
            dest: /usr/lib/slack/libnode.so
            owner: root
            group: root
            mode: 0755
            state: link
      when: libnode.stat.exists == false
    
    - name: configure chris' group memberships
      user:
        name: chris
        groups: 
          - wheel
          - disk

    - name: install rpmfusion packages
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm

    - name: install fedora video packages
      package:
        name: gstreamer-plugins-base, gstreamer1-plugins-base, gstreamer-plugins-bad, gstreamer-plugins-ugly, gstreamer1-plugins-ugly, gstreamer-plugins-good-extras, gstreamer1-plugins-good-extras, gstreamer1-plugins-bad-freeworld, ffmpeg, gstreamer-ffmpeg, vlc

    - name: install other packages
      package: 
        name: mediawriter, icedtea-web.noarch, elfutils-devel, grive2, kernel-devel, vinagre, gimp, pdfmod, NetworkManager-openvpn-gnome, nmap, gcc, gdb, lftp, ftp, iptraf-ng, nmon, iperf, vnstat, sysstat, openscap, openscap-scanner, openscap-utils, openscap-python, openscap-containers
        state: latest

#    - name: install Sun Java (for TOS) #BUG with Java & Coreutils
#      package:
#        name: /export/archive/Linux/Java/jdk-8u192-linux-x64.rpm
#        state: present
    
    - name: install Sun Java (for TOS)
      command: rpm -ivh /export/archive/Linux/Java/jdk-8u192-linux-x64.rpm
      become: true
      ignore_errors: true   # set this because yum cannot install this due to deps
      args: 
        warn: false

    - name: set Sun Java as default (for TOS)
      alternatives:
        name: java
        path: /usr/java/jdk1.8.0_192-amd64/jre/bin/java

