---
#
# Configure Server0
#

# CentOS 8 Prerequisites: 
#	python3
#	policycoreutils-python3
#	rsync

- hosts: server0
  become: yes

  roles:
    - role: sm-register
      tags: ['sm-register']

    - role: selinux
      tags: ['selinux']

    - role: setup-br0
      tags: ['setup-br0']

    - role: http-repo
      tags: ['http-repo']

#    - role: config-local-repos
#      tags: ['config-local-repos']

    - role: apply-updates
      tags: ['apply-updates']

    - role: time-server
      tags: ['time-server']

    - role: tftp-server
      tags: ['tftp-server']

    - role: ssh-config
      tags: ['ssh-config']

    - role: shell-env #including both ssh-keys on server and p51s ??
      tags: ['shell-env']

    - role: syncscripts
      tags: ['syncscripts']

    - role: kickstart
      tags: ['kickstart']

    - role: samba-server
      tags: ['samba-server']

    - role: nfs-server
      tags: ['nfs-server']

    - role: rsync-server
      tags: ['rsync-server']

    - role: setup-epel
      tags: ['setup-epel']

    - role: virt-server
      tags: ['virt-server']

    - role: plex-server
      tags: ['plex-server']

#    - role: apcupsd
#      tags: ['apcupsd']

#    - role: openvpn-server
#      tags: ['openvpn-server']

#    - role: fail2ban
#      tags: ['fail2ban']

#    - role: syslog
#      tags: ['syslog']

#    - role: backup
#      tags: ['backup']

    - role: insights-register
      tags: ['insights']

    - role: reboot-if-required
      tags: ['reboot-if-required']


  tasks:
    - name: install other packages 
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - elfutils-devel
        - kernel-devel
        - nmap
        - gcc
        - gdb
        - lftp
        - ftp
        - openscap
        - openscap-scanner
        - openscap-utils
        - openscap-python3
        - python3-botocore
        - python3-boto3
        - python3-pyvmomi
        - ansible
      tags:
        - localpkgs

    - name: install other fedora packages 
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - openscap-containers
        - openscap-daemon
        - python3-boto
        - openwsman-winrs.x86_64
      when: 
        - ansible_distribution == "Fedora"
