---
#
# Configure Server0
#

- hosts: server0
  become: yes

  roles:
    - role: config-local-repos
      tags: ['config-local-repos']

    - role: config-local-rpmfusion-repos
      tags: ['config-local-rpmfusion-repos']

    - role: setup-br0
      tags: ['setup-br0']

    - role: disable-ipv6
      tags: ['disable-ipv6']

    - role: selinux
      tags: ['selinux']

    - role: limit-kernels
      tags: ['limit-kernels']

    - role: ssh-config
      tags: ['ssh-config']

    - role: shell-env #including both ssh-keys on server and p51s ??
      tags: ['shell-env']

    - role: set-default-editor
      tags: ['set-default-editor']

    - role: syncscripts
      tags: ['syncscripts']

#    - role: masquerade
#      tags: ['masquerade']

    - role: dnsmasq
      tags: ['dnsmasq']

    - role: apply-updates
      tags: ['apply-updates']

    - role: samba-server
      tags: ['samba-server']

    - role: time-server
      tags: ['time-server']

    - role: tftp-server
      tags: ['tftp-server']

    - role: virt-server
      tags: ['virt-server']

    - role: config-local-virtio-win-repos
      tags: ['config-local-virtio-win-repos']

    - role: kickstart
      tags: ['kickstart']

    - role: rsync-server
      tags: ['rsync-server']

    - role: setup-epel
      tags: ['setup-epel']

    - role: rsyslog-server
      tags: ['rsyslog-server']

    - role: http-repo
      tags: ['http-repo']

## DON'T AUTO REBOOT IF RUNNING KVM VMs
## At least not until the role is modified to accomodate it
#    - role: reboot-if-required
#      tags: ['reboot-if-required']


  tasks:
    - name: install other packages 
      ansible.builtin.package:
        name: nmap, lftp, ftp, openscap, openscap-scanner, openscap-utils, openscap-python3, python3-botocore, python3-boto3, python3-pyvmomi, ansible, screen, virtio-win, xar, fuse-sshfs, git
        state: latest
      tags:
        - localpkgs

    - name: install other fedora packages 
      ansible.builtin.package:
        name: openscap-containers, openscap-daemon, python3-boto, openwsman-winrs.x86_64, vnstat, nmon
        state: latest
      when: 
        - ansible_distribution == "Fedora"
      tags:
        - localpkgs

    - name: start and enable vnstat
      ansible.builtin.service:
        name: vnstat
        state: started
        enabled: yes
