---
- name: rhel/centos 7+ setup sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when:
      - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
      - ansible_distribution_major_version >= "7"
  notify: restart sshd service

- name: rhel/centos 5/6 setup sshd_config
  ansible.builtin.template:
    src: sshd_config-older.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when:
      - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "5"
  notify: restart sshd service

- name: fedora 28+ setup sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when:
      - ansible_distribution == "Fedora"
      - ansible_distribution_major_version >= "28"
  notify: restart sshd service

# See Details: https://www.redhat.com/en/blog/openssh-scp-deprecation-rhel-9-what-you-need-know
- name: disable scp
  ansible.builtin.file:
    path: /etc/ssh/disable_scp
    state: touch
    mode: 0600
    owner: root
    group: root
  notify: restart sshd service

# Disable HMAC-SHA1 as it is insecure
# See: https://access.redhat.com/articles/7041246
- name: disable HMAC-SHA1
  ansible.builtin.lineinfile: 
    path: /etc/crypto-policies/policies/modules/DISABLE-INSECURE-HMAC-SHA1.pmod
    line: "mac@ssh = -HMAC-SHA1"
    create: true
    mode: 0600
    owner: root
    group: root
  notify: restart sshd service
    

# Update crypto policy
- name: update crypto policy
  ansible.builtin.command: update-crypto-policies --set DEFAULT:DISABLE-INSECURE-HMAC-SHA1
  become: yes

