---
- name: Set timezone to {{TIMEZONE}}
  ansible.builtin.timezone:
    name: "{{TIMEZONE}}"

- name: install chrony and firewalld
  ansible.builtin.package:
    name: chrony,firewalld
    state: latest

- name: setup chrony.conf file
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: restart chronyd

- name: start and enable chronyd
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes

- name: make sure firewalld is running and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: open firewall ports for chrony
  ansible.builtin.firewalld:
    zone: "{{trusted_firewall_zone}}"
    service: ntp
    immediate: yes
    state: enabled
    permanent: yes
...
