---
- name: Install bind,bind-chroot, bind-utils, and firewalld
  ansible.builtin.package:
    name: bind,bind-chroot,bind-utils,firewalld
    state: latest
  notify: restart named

- name: configure firewall for DNS services
  ansible.builtin.firewalld:
    zone: "{{trusted_firewall_zone}}"
    service: dns
    immediate: yes
    state: enabled
    permanent: yes

- name: install named.conf
  ansible.builtin.template:
    src: named.conf.{{ansible_hostname}}.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
  notify: restart named

- name: deploy zone files
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/var/named/{{item}}"
    mode: 0640
    owner: root
    group: named
  with_items:
    - "{{zone_file_list}}"
  notify: restart named

- name: start and enable named service 
  ansible.builtin.service:
    name: named
    state: started
    enabled: yes

