---
- name: rhel/centos 7+ setup sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when:
      - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
      - ansible_distribution_major_version >= "7"
  notify: restart sshd service

- name: rhel/centos 5/6 setup sshd_config
  template:
    src: sshd_config-older.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when:
      - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "5"
  notify: restart sshd service

- name: fedora 28+ setup sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when:
      - ansible_distribution == "Fedora"
      - ansible_distribution_major_version >= "28"
  notify: restart sshd service

- name: create .ssh directories
  file:
    path: "~{{item}}/.ssh"
    state: directory
    mode: 0700
    owner: "{{item}}"
    group: "{{item}}"
    seuser: unconfined_u
    serole: object_r
    setype: ssh_home_t
    selevel: s0
  with_items:
    - "{{ssh_keygen_users}}"

- name: generate RSA ssh keys
  command: "ssh-keygen -q -f ~{{item}}/.ssh/id_rsa -t rsa -N ''"
  args:
    creates: "~{{item}}/.ssh/id_rsa"
  with_items:
    - "{{ssh_keygen_users}}"
  tags: generate_keys

- name: set permission on ssh private keys
  file:
    path: "~{{item}}/.ssh/id_rsa"
    state: file
    mode: 0600
    owner: "{{item}}"
    group: "{{item}}"
    seuser: unconfined_u
    serole: object_r
    setype: ssh_home_t
    selevel: s0
  with_items:
    - "{{ssh_keygen_users}}"

- name: set permission on ssh public keys
  file:
    path: "~{{item}}/.ssh/id_rsa.pub"
    state: file
    mode: 0644
    owner: "{{item}}"
    group: "{{item}}"
    seuser: unconfined_u
    serole: object_r
    setype: ssh_home_t
    selevel: s0
  with_items:
    - "{{ssh_keygen_users}}"

- name: configure chris' mbp key for "{{ansible_user}}" 
  authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: "{{ lookup('file', '~chris/.ssh/id_rsa.pub') }}"

- name: configure chris' server0 key for "{{ansible_user}}" 
  authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: "{{ lookup('file', '~chris/.ssh/chris-server0-id_rsa.pub') }}"

- name: configure chris' x1carbon key for "{{ansible_user}}" 
  authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: "{{ lookup('file', '~chris/.ssh/chris-x1carbon-id_rsa.pub') }}"

- name: lockdown "{{ansible_user}}" authorized_keys
  file:
    path: "~{{ansible_user}}/.ssh/authorized_keys"
    state: file
    mode: 0600
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    seuser: unconfined_u
    serole: object_r
    setype: ssh_home_t
    selevel: s0

- name: remove root's authorized_keys 
  file:
    path: "~root/.ssh/authorized_keys"
    state: absent
...

