---
- name: setup br0 with nmcli
  community.general.nmcli:
    conn_name: "{{ primary_bridge }}"
    type: bridge
    ip4: "{{ primary_ipaddr }}"
    gw4: "{{ primary_gateway }}"
    state: present
  notify: restart NetworkManager

- name: reconfigure firewall for bridge
  ansible.builtin.firewalld:
    zone: "{{public_firewall_zone}}"
    interface: "{{primary_bridge}}"
    permanent: yes
    state: enabled
    immediate: yes

- name: Set ip forwarding sysctl and reload if necessary
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  notify: restart NetworkManager
