---
- name: install bridge-utils package
  package:
    name: bridge-utils
    state: latest
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"

- name: install /etc/sysconfig/network-scripts/ifcfg-br0 template on RHEL6/7
  template:
    src: ifcfg-br0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-br0
    owner: root
    group: root
    mode: 0644
  notify: restart network
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"

- name: install /etc/sysconfig/network-scripts/ifcfg-br0 template on RHEL8
  template:
    src: ifcfg-br0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-br0
    owner: root
    group: root
    mode: 0644
  notify: restart NetworkManager
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: install /etc/sysconfig/network-scripts/ifcfg-eth0 on RHEL6/7
  template:
    src: ifcfg-eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: 0644
  notify: restart network
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"

- name: install /etc/sysconfig/network-scripts/ifcfg-eth0 template on RHEL8
  template:
    src: ifcfg-eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: 0644
  notify: restart NetworkManager
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- firewalld:
    zone: "{{public_firewall_zone}}"
    interface: "{{primary_bridge}}"
    permanent: true
    state: enabled

- name: Set ip forwarding and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
