---
# handlers file for mbp-dnsmasq

- name: restart dnsmasq
  ansible.builtin.shell: "launchctl stop homebrew.mxcl.dnsmasq; launchctl start homebrew.mxcl.dnsmasq"
  become: yes

- name: restart_vmware_networking
  ansible.builtin.script: ~{{ansible_user}}/scripts/{{inventory_hostname}}/restart_vmware_network.sh
  become: yes
