---
- name: restart atalk
  ansible.builtin.service:
    name: netatalk
    state: restarted
    enabled: yes

- name: restart avahi-daemon
  ansible.builtin.service:
    name: avahi-daemon
    state: restarted
    enabled: yes

- name: reconfig authselect
  ansible.builtin.command: /usr/bin/authselect apply-changes

