---
- name: include luks key data
  include_vars:
    file: luks-key.yml

- name: synchronize files/syslinux content to {{tftpbootdir}}
  synchronize:
    src: files/syslinux/
    dest: "{{ tftpbootdir }}"
    archive: yes
    delete: yes
    links: yes
    recursive: yes
    times: yes
    rsync_opts: 
      - "--exclude=pxelinux.cfg"
      - "--exclude=images"
  become: yes

- name: create {{tftpbootdir}}/{pxelinux.cfg,images} directories
  file:
    path: "{{tftpbootdir}}/{{item}}"
    owner: root
    group: wheel
    mode: 0755
    state: directory
  with_items:
    - images
    - pxelinux.cfg

- name: deploy {{tftpbootdir}}/pxelinux.cfg/default
  copy:
    src: default
    dest: "{{tftpbootdir}}/pxelinux.cfg/default"
    owner: root
    group: wheel
    mode: 0644

- name: create {{tftpbootdir}}/pxelinux.cfg/Linux directory
  file:
    path: "{{tftpbootdir}}/pxelinux.cfg/Linux"
    owner: root
    group: wheel
    mode: 0755
    state: directory

- name: deploy {{tftpbootdir}}/pxelinux.cfg/Linux Files
  template:
    src: "{{item}}.j2"
    dest: "{{tftpbootdir}}/pxelinux.cfg/Linux/{{item}}"
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - "{{pxelinux_files}}"

################################################################################
# RHEL images Files copies                                                     #
################################################################################
- name: create RHEL {{tftpbootdir}}/images/linux/rhel/version/arch directories
  file:
    path: "{{tftpbootdir}}/images/rhel/{{item[0]}}/{{item[1]}}"
    owner: root
    group: wheel
    mode: 0755
    state: directory
    recurse: yes
  with_nested:
    - "{{rhel_versions}}"
    - "{{rhel_architectures}}"

- name: synchronize RHEL pxeboot content to {{tftpbootdir}}/images/fedora
  synchronize:
    src: "{{installdir}}/Linux/rhel/{{item[0]}}/{{item[1]}}/images/pxeboot/"
    dest: "{{tftpbootdir}}/images/rhel/{{item[0]}}/{{item[1]}}/"
    archive: yes
    delete: yes
    links: yes
    times: yes
  delegate_to: "{{ inventory_hostname }}"
  with_nested:
    - "{{rhel_versions}}"
    - "{{rhel_architectures}}"

################################################################################
# CentOS images Files copies                                                   #
################################################################################
- name: create CentOS 7 {{tftpbootdir}}/images/linux/centos/version/arch directories
  file:
    path: "{{tftpbootdir}}/images/centos/7/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
    recurse: yes
  with_items:
    - "{{centos_architectures}}"

- name: synchronize CentOS 7 content to {{tftpbootdir}}/images/centos
  synchronize:
    src: "{{installdir}}/Linux/centos/7/os/{{item}}/images/pxeboot/"
    dest: "{{tftpbootdir}}/images/centos/7/{{item}}/"
    archive: yes
    delete: yes
    links: yes
    times: yes
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - "{{centos_architectures}}"

- name: create CentOS 8+ {{tftpbootdir}}/images/linux/centos/version/arch directories
  file:
    path: "{{tftpbootdir}}/images/centos/8/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
    recurse: yes
  with_items:
    - "{{centos_architectures}}"

- name: synchronize CentOS 8+ pxeboot content to {{tftpbootdir}}/images/centos
  synchronize:
    src: "{{installdir}}/Linux/centos/8/BaseOS/{{item}}/os/images/pxeboot/"
    dest: "{{tftpbootdir}}/images/centos/8/{{item}}/"
    archive: yes
    delete: yes
    links: yes
    times: yes
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - "{{centos_architectures}}"

################################################################################
# Fedora images Files copies                                                   #
################################################################################
- name: create Fedora {{tftpbootdir}}/images/linux/fedora/version/arch directories
  file:
    path: "{{tftpbootdir}}/images/fedora/{{item[0]}}/{{item[1]}}"
    owner: root
    group: wheel
    mode: 0755
    state: directory
    recurse: yes
  with_nested:
    - "{{fedora_versions}}"
    - "{{fedora_architectures}}"

- name: synchronize Fedora pxeboot content to {{tftpbootdir}}/images/fedora
  synchronize:
    src: "{{installdir}}/Linux/fedora/releases/{{item[0]}}/Everything/{{item[1]}}/os/images/pxeboot/"
    dest: "{{tftpbootdir}}/images/fedora/{{item[0]}}/{{item[1]}}/"
    archive: yes
    delete: yes
    links: yes
    times: yes
  delegate_to: "{{ inventory_hostname }}"
  with_nested:
    - "{{fedora_versions}}"
    - "{{fedora_architectures}}"

################################################################################
# Ubuntu images Files copies                                                   #
################################################################################
- name: create {{tftpbootdir}}/images/ubuntu/server/version/architeture directory
  file:
    path: "{{tftpbootdir}}/images/ubuntu/server/{{item[0]}}/{{item[1]}}/"
    owner: root
    group: wheel
    mode: 0755
    state: directory
    recurse: yes
  with_nested:
    - "{{ubuntu_server_versions}}"
    - "{{ubuntu_server_architectures}}"

#- name: synchronize Ubuntu Server netboot content to {{tftpbootdir}}/images/ubuntu
#  synchronize:
#    src: "{{installdir}}/Linux/ubuntu/server/{{item[0]}}/{{item[1]}}/install/netboot/ubuntu-installer/{{item[1]}}/"
#    dest: "{{tftpbootdir}}/images/ubuntu/server/{{item[0]}}/{{item[1]}}/"
#    archive: yes
#    delete: yes
#    links: yes
#    times: yes
#  delegate_to: "{{ inventory_hostname }}"
#  with_nested:
#    - "{{ubuntu_server_versions}}"
#    - "{{ubuntu_server_architectures}}"

################################################################################
# OpenBSD images Files copies                                                  #
################################################################################
- name: create OpenBSD {{tftpbootdir}}/images/linux/rhel/architecture directories
  file:
    path: "{{tftpbootdir}}/images/openbsd/{{item}}"
    owner: root
    group: wheel
    mode: 0755
    state: directory
    recurse: yes
  with_items:
    - "{{openbsd_versions}}"

################################################################################
# vmware images Files copies                                                   #
################################################################################
- name: setup OpenBSD network boot on server0
  block:
    - name: create vmware {{tftpbootdir}}/images/linux/rhel/architecture directories
      file:
        path: "{{tftpbootdir}}/images/vmware/{{item}}"
        owner: root
        group: wheel
        mode: 0755
        state: directory
        recurse: yes
      with_items:
        - "{{vmware_versions}}"
  when: ansible_hostname == "server0"

- name: restore selinux context for {{tftpbootdir}}
  command: "restorecon -RFv {{tftpbootdir}}"

################################################################################
# Deploy kickstart configuration files                                         #
################################################################################
- name: make sure {{ks_config_dir}} exists
  file:
    path: "{{ks_config_dir}}"
    state: directory
    owner: chris
    group: chris
    mode: 0755

- name: deploy {{ks_config_dir}} Files
  template:
    src: "ks-configs/{{item}}.j2"
    dest: "{{ks_config_dir}}/{{item}}"
    owner: chris
    group: chris
    mode: 0644
  with_items:
    - "{{ks_configs_list}}"

- name: deploy callback-service templates to {{config_files_url}} Files
  template:
    src: "{{item}}.j2"
    dest: "{{config_files_dir}}/{{item}}"
    owner: chris
    group: chris
    mode: 0755
  with_items:
    - rhel6-callback-service.sh
    - rhel7-callback.service

- name: restore selinux context for {{ks_config_dir}}
  command: "restorecon -RFv {{ks_config_dir}}"
  tags: restorecon

