---
- name: install EPEL on RHEL/CentOS 7
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"  
    - ansible_distribution_major_version == "7"

- name: install EPEL on RHEL/CentOS 6
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    state: present
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"  
    - ansible_distribution_major_version == "6"
