---
- name: install EPEL on RHEL/CentOS
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"  
