---
- name: Install/Update rsyslog/firewalld
  ansible.builtin.package: 
    name: rsyslog, firewalld
    state: latest
  notify: restart rsyslog

- name: Install /etc/rsyslog.conf
  ansible.builtin.template:
    src: rsyslog-client.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart rsyslog

- name: Start and Enable rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes

