# {{ansible_managed}}

# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
export PS1="`whoami`@`hostname -s`:\$PWD> "

export EDITOR=/usr/bin/vi

export ANSIBLE_CONFIG=~chris/playbooks/ansible.cfg
export ANSIBLE_NOCOWS=1

alias gcp="git add .;git commit -m 'Latest Commits' ; git push"
