---
- name: Install tftp-server
  ansible.builtin.package:
    name: tftp-server,firewalld
    state: latest
  notify: restart tftp

- name: configure firewall for TFTP services
  ansible.builtin.firewalld:
    zone: "{{trusted_firewall_zone}}"
    service: tftp
    immediate: yes
    state: enabled
    permanent: yes

- name: start and enable tftp service
  ansible.builtin.service:
    name: tftp
    state: started
    enabled: yes
