- name: Perform RHEL-6/CentOS-6 Specific Confgurations
  import_tasks: rhel-centos6.yml
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: Perform RHEL-7/CentOS-7 Specific Confgurations
  import_tasks: rhel-centos7.yml
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Perform RHEL-8/CentOS-8 Specific Confgurations
  import_tasks: rhel-centos8.yml
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: Perform Fedora 28+ Specific Confgurations
  include: fedora.yml repoName="{{item}}"     ## DEPRECATION WARNING TO FIX HERE
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version >= "28"  # 28,29...
  with_items:  "{{fedora_repos_list}}"

