#
# Playbook to Perform Common Configuration on RHEL5 Systems
# Author: Chris Tjon
#
# Tasks Performed:
#  - Install Of GPG Keys for Distribution Repo and EPEL
#  - Configuration of Local Distribution Repo and Local EPEL Repo
#  - Disable Public Internet Repos for Distribution and EPEL
#  - Install Required Packages
#  - Configure for Retention of only latest kernel
#  - Modify inittab for non-graphical boot
#

---
- name: rhel5.yml - install rhel rpm_gpg_key
  rpm_key:
    state: present
    key: "{{ rhel_gpg_key_url }}"

- name: rhel5.yml - setup /etc/yum.repos.d/tjon-rhel5.repo
  template:
    src: tjon-rhel5.repo.j2
    dest: /etc/yum.repos.d/tjon-rhel5.repo
    owner: root
    group: root
    mode: 0644

- name: rhel5.yml - setup /etc/yum.repos.d/tjon-epel5.repo
  template:
    src: tjon-epel5.repo.j2
    dest: /etc/yum.repos.d/tjon-epel5.repo
    owner: root
    group: root
    mode: 0644

- name: rhel5.yml - install yum-utils
  command: yum -y install yum-utils
  args:
    warn: false

- name: configure to boot to runlevel 3
  replace:
    path: /etc/inittab
    regexp: '^id:5:initdefault:\n'
    replace: 'id:3:initdefault:\n'
    owner: root
    group: root
    mode: 0644

- name: rhel5.yml - Clean up all but the most recent kernel
  command: package-cleanup --oldkernels --count="{{installed_kernel_limit}}" -y
...
