---
#- name: disable fedora internet repositories
#  ansible.builtin.command: dnf config-manager --set-disabled "{{ repoName }}" --save
#  args:
#    warn: false # set warn=false to avoid warnings about dnf command/module
#  ignore_errors: yes

- name: Make a distro repo file backup directory /etc/yum.repos.d/save
  ansible.builtin.file:
    path: /etc/yum.repos.d/save
    state: directory
    mode: '0755'

- name: Backup original distro repo files
  block:
    - name: Check to see if repo files require backup
      ansible.builtin.stat:
        path: "/etc/yum.repos.d/{{repoName}}.repo"
      register: result

    - name: Backup original repo files to /etc/yum.repos.d/save directory
      ansible.builtin.copy:
        src: "/etc/yum.repos.d/{{repoName}}.repo"
        dest: "/etc/yum.repos.d/save/{{repoName}}.repo"
        owner: root
        group: root
        mode: '0644'
        remote_src: true
      when: result.stat.exists
        
    - name: Remove original repo files from /etc/yum.repos.d
      ansible.builtin.file:
        path: "/etc/yum.repos.d/{{repoName}}.repo"
        state: absent

    - name: Install new repo files in /etc/yum.repos.d for local server
      ansible.builtin.copy:
        src: "{{installdir}}/Linux/ConfigFiles/etc/yum.repos.d/{{linux_install_server_hostname}}-local/{{repoName}}-local.repo"
        dest: "/etc/yum.repos.d/{{repoName}}-local.repo"
        owner: root
        group: root
        remote_src: true
        mode: '0644'

  become: true
...
