---
- name: Restart Firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
    enabled: yes

- name: Restart OpenVPN 
  ansible.builtin.service:
    name: "{{item}}"
    enabled: yes
    state: restarted
  with_items:
    - openvpn-server@1194udp
    - openvpn-server@443tcp

