---
- name: include sm_creds
  include_vars:
    file: group_vars/sm_creds.yml

- name: Install Packages for Insights
  ansible.builtin.package:
    name: insights-client
    state: present
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version >= "6"

- name: register for insights
  ansible.builtin.command: insights-client --register
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version >= "6"

