---
- name: restart nfs server
  ansible.builtin.service:
    name: nfs-server
    enabled: yes
    state: restarted

- name: restart firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: yes
    state: restarted

