#
# RPMFUSION includes/excludes
#
rpmfusion_rsync_server: download1.rpmfusion.org

el_rpmfusion_version_includes_list:
  - 8
  - 9

el_rpmfusion_version_excludes_list:
  - 6
  - 7

fedora_rpmfusion_version_includes_list:
  - 40
  - 41

rpmfusion_previous_release_ones_digit: 6
fedora_rpmfusion_version_excludes_list:
  - '3[1-{{rpmfusion_previous_release_ones_digit}}]'


rpmfusion_repo_includes_list:
  - 'x86_64'
  - 'source'
  - 'aarch64'

rpmfusion_repo_excludes_list:
  - 'i386'
  - 'ppc64le'
  - 's390x'
  - 'development'
  - 'testing'
  - 'rawhide'
  - 'debug'
  - 'fedora-secondary'
