---
- name: include azure_creds
  include_vars:
    file: azure_creds.yml

- name: Add Microsoft GPG key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: setup repo to install azure-cli
  yum_repository:
    name: azure-cli
    description: Azure CLI
    file: /etc/yum.repos.d/azure-cli
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    enabled: yes
    metadata_expire: 7d
    repo_gpgcheck: 0
    #type: rpm
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    skip_if_unavailable: false
    keepcache: false
    failovermethod: priority

- name: Fedora 28+ Install azure-cli and other packages
  package:
    name: azure-cli, python3-azure-sdk, python3-azure-storage, python3-msrestazure, python-azure-sdk-doc, fence-agents-azure-arm
    state: latest
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version >= "28"

- name: RHEL 6+ Install azure-cli and other packages
  package:
    name: azure-cli
    state: latest
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version >= "6"

- name: "create /home/{{ansible_user_id}}/.azure directory for azure creds"
  file:
    path: "/home/{{ansible_user_id}}/.azure"
    state: directory
    mode: 0700

#    path: "/home/{{ansible_user_id}}/.azure"

- name: deploy azure creds
  template:
    src: azure_creds.j2
    dest: "/home/{{ansible_user_id}}/.azure/credentials"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0600

