---
- name: Install Performance Monitoring Tools
  ansible.builtin.package:
    name: vnstat, nmon
    state: latest

- name: start and enable vnstat
  ansible.builtin.service:
    name: vnstat
    state: started
    enabled: yes

