---
- name: restart network
  service:
    name: network
    state: restarted
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"

- name: restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version >= "8"
