---
- name: shutdown RHEL/CentOS 6 and older hosts
  command: /sbin/shutdown -h now
  become: yes
  when:
    - ((ansible_distribution == "RedHat") or (ansible_distribution == "CentOS"))
    - ((ansible_distribution_major_version <= "6"))

- name: shutdown RHEL/CentOS 7 and newer
  command: /usr/bin/systemctl poweroff
  become: yes
  when:
    - ((ansible_distribution == "RedHat") or (ansible_distribution == "CentOS"))
    - ((ansible_distribution_major_version >= "7"))

- name: shutdown Fedora 30 and newer
  command: /usr/bin/systemctl poweroff
  become: yes
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version >= "30"

- name: Wait for SSH port to be stopped
  wait_for:
    host: "{{ ansible_ssh_host }}"
    port: 22
    state: stopped
