---
# tasks file for mbp-ksconfigs

- name: make sure {{ks_config_dir}} exists
  file:
    path: "{{ks_config_dir}}"
    state: directory
    owner: chris
    group: staff
    mode: 0755

- name: deploy {{ks_config_dir}} Files
  template:
    src: "ks-configs/{{item}}.j2"
    dest: "{{ks_config_dir}}/{{item}}"
    owner: chris
    group: staff
    mode: 0644
  with_items:
    - "{{ks_configs_list}}"

- name: make sure {{linux_config_files_dir}} exists
  file:
    path: "{{linux_config_files_dir}}"
    state: directory
    owner: chris
    group: staff
    mode: 0755

- name: deploy callback-service templates to {{config_files_url}} Files
  template:
    src: "{{item}}.j2"
    dest: "{{linux_config_files_dir}}/{{item}}"
    owner: chris
    group: staff
    mode: 0755
  with_items:
    - rhel6-callback-service.sh
    - rhel7-callback.service
