---
- name: Set Timezone
  ansible.builtin.timezone:
    name: "{{TIMEZONE}}"

- name: setup time clients for RHEL/Centos/Fedora Systems
  block:
    - name: install chrony
      ansible.builtin.package:
        name: chrony
        state: latest

    - name: setup chrony.conf file
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: 0644
      notify: restart chronyd

    - name: start and enable chronyd
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
  when: ((ansible_distribution == "RedHat" or ansible_distribution == "CentOS") and ansible_distribution_major_version >= "7") or (ansible_distribution == "Fedora" and ansible_distribution_major_version >= "28")

- name: setup NTP Client for RHEL-5 Systems
  block:
    - name: setup RHEL-5 system timezone
      ansible.builtin.template:
        src: templates/clock.j2
        dest: /etc/sysconfig/clock
        owner: root
        group: root
        mode: 0644
      tags: ntpd

    - name: setup RHEL-5 ntp time synchronization
      ansible.builtin.template:
        src: templates/ntp.conf.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644
      tags: ntpd

    - name: restart and enable RHEL-5 ntpd
      ansible.builtin.service:
        name: ntpd
        state: restarted
        enabled: yes
      tags: ntpd
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "5"

...
