---
# Install Prequisite Packages
# mkdir /mnt/install
# configure /etc/fstab to mount /mnt/install at boot
# mount /etc/install
# install sync-RHrepo.sh
# crontab sync-RHrepo.sh
# setup log copy back to server
# reboot

- name: Install nfs-utils/yum-utils/createrepo 
  ansible.builtin.package:
    name: nfs-utils, yum-utils, createrepo
    state: latest

- name: Create {{ nfs_mount }} mountpoint
  ansible.builtin.file:
    path: "{{ nfs_mount }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Configure "{{ nfs_mount }}" fstab entry to auto mount NFS filesystem
  ansible.builtin.mount: 
    name: "{{ nfs_mount }}"
    src: "{{ nfs_server }}"
    fstype: nfs
    opts: hard,intr
    dump: "0"
    passno: "2"
    state: mounted

- name: Create {{ scripts_dir }}
  ansible.builtin.file:
    path: "{{ scripts_dir }}"
    owner: "{{ scripts_owner }}"
    group: "{{ scripts_group }}"
    mode: 0755
    state: directory
  
- name: Create {{ logs_dir }}
  ansible.builtin.file:
    path: "{{ logs_dir }}"
    owner: "{{ logs_owner }}"
    group: "{{ logs_group }}"
    mode: 0755
    state: directory
  
- name: deploy {{script_name}}.j2 to {{scripts_dir}}/{{script_name}}
  ansible.builtin.template:
    src: "{{ script_name }}.j2"
    dest: "{{ scripts_dir }}/{{ script_name }}"
    owner: "{{ scripts_owner }}"
    group: "{{ scripts_group }}"
    mode: 0755
  tags: deploy_script

- name: configure cronjob to run script
  ansible.builtin.cron:
    name: "Sync RH Repo"
    weekday: "{{ansible_distribution_major_version|int - 6}}"
    minute: "30"
    hour: "{{ansible_distribution_major_version|int - 6}}"
    job: "{{ scripts_dir }}/{{ script_name }} > {{ logs_dir }}/{{ log_name }} 2>&1"

- name: configure cronjob to reset permissions on home directory
  ansible.builtin.cron:
    name: "Reset Permisssions on home directory"
    minute: "0"
    hour: "{{ansible_distribution_major_version|int - 4}}"
    job: "chown -R chris:chris /home/chris"
...
