---
- name: debug ansible_distribution var
  ansible.builtin.debug:
    var: ansible_distribution

- name: debug ansible_distribution_major_version var
  ansible.builtin.debug:
    var: ansible_distribution_major_version

- name: Install and/or Update fail2ban on RHEL6
  ansible.builtin.package:
    name: fail2ban
    state: latest
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: Install and/or Update fail2ban on RHEL7+
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - fail2ban-server
    - fail2ban-firewalld
  when:
    - ((ansible_distribution == "RedHat" or ansible_distribution == "CentOS") and  (ansible_distribution_major_version >= "7")) or ((ansible_distribution == "Fedora") and (ansible_distribution_major_version >= "28"))

- name: Start and Enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes

- name: deploy fail2ban on Everything Else
  block:
#    - name: deploy fail2ban.conf template
#      ansible.builtin.template:
#        src: fail2ban.conf.j2
#        dest: /etc/fail2ban/fail2ban.conf
#        owner: root
#        group: root
#        mode: 0644
#      notify: restart fail2ban

    - name: deploy jail.local template
      ansible.builtin.template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: 0644
      notify: restart fail2ban
#  when:
#    - ((ansible_distribution == "RedHat" or ansible_distribution == "CentOS") and (ansible_distribution_major_version > "5")) or ((ansible_distribution == "Fedora") and (ansible_distribution_major_version >= "28"))

...
