---
plex_owner: chris
plex_group: plex
plex_storage_vg: plexvg
plex_storage_lv: plexlv
#plex_storage_lv_size: 5T
plex_storage_lv_size: 100g
plex_storage_fs_type: xfs
plex_storage_path: /export/plex
plex_local_net: 172.16.1.0
plex_local_net_netmask: 255.255.255.0
