---
- name: set network tunables
  ansible.builtin.command:
    cmd: "ethtool -K {{item.0}} {{item.1.name}} {{item.1.value}}"
  with_nested:
    - "{{ network_interfaces_to_tune }}"
    - "{{ tcp_stack_features_to_tune }}"

- name: set jumbo frames
  ansible.builtin.command:
    cmd: "nmcli connection modify {{item}} 802-3-ethernet.mtu 9000"
  with_items:
    - "{{ network_interfaces_to_tune }}"

# THIS IS BROKEN - NOT SURE WHY YET?
#- name: set jumbo frames
#  nmcli:
#    conn_name: "{{item}}"
#    mtu: 9000
#    type: ethernet
#    state: present
#  with_items:
#    - "{{ nmcli_connections }}"
