---
- name: install dnsmasq.conf file
  ansible.builtin.template:
    src: dnsmasq.conf.{{ansible_hostname}}.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: dnsmasq
    mode: 0644
  notify: restart dnsmasq

- name: modify dhcp config
  ansible.builtin.blockinfile:
    path: /etc/config/dhcp
    block: |
      config boot 'linux'
      	option filename 'pxelinux.0'
      	option serveraddress '172.16.1.2'
      	option servername 'server0.internal.tjon.net'
  notify: restart dnsmasq

- name: install /etc/hosts file
  ansible.builtin.copy:
    src: "hosts.{{ansible_hostname}}"
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
...
