---
#- name: install dnsmasq.conf file
#  template:
#    src: dnsmasq.conf.{{ansible_hostname}}.j2
#    dest: /etc/dnsmasq.conf
#    owner: root
#    group: dnsmasq
#    mode: 0644
#  notify: restart dnsmasq
#
#- name: install dnsmasq.d/pxe.conf file
#  template:
#    src: pxe.conf.{{ansible_hostname}}.j2
#    dest: /etc/dnsmasq.d/pxe.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify: restart dnsmasq
#  when: pxe_enabled == true
#
#- name: configure dnsmasq for DHCP
#  block: 
#    - name: install dnsmasq.d/dhcp.conf file
#      template:
#        src: dhcp.conf.{{ansible_hostname}}.j2
#        dest: /etc/dnsmasq.d/dhcp.conf
#        owner: root
#        group: root
#        mode: 0644
#      notify: restart dnsmasq
#  when: dhcp_enabled == true

#- name: configure firewall for DHCP # Need this for PXE
#  firewalld:
#    zone: "{{trusted_firewall_zone}}"
#    service: dhcp
#    immediate: yes
#    state: enabled
#    permanent: yes
#  notify: restart dnsmasq
#  when: dhcp_enabled == true

- name: install /etc/hosts file
  copy:
    src: "hosts.{{ansible_hostname}}"
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
...
