---
- name: Install virtio-win repo
  ansible.builtin.get_url:
    url: https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo 
    dest: /etc/yum.repos.d/virtio-win.repo
    mode: '0644'
    owner: root
    group: root
