---
- name: install packages
  package:
    name: dnsmasq,tftp-server,tftp,httpd,firewalld
    state: latest

- name: start and enable dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: true

- name: install dnsmasq.conf file
  template:
    src: dnsmasq.conf.{{ansible_hostname}}.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: dnsmasq
    mode: 0644
  notify: restart dnsmasq

- name: install dnsmasq.d/pxe.conf file
  template:
    src: pxe.conf.{{ansible_hostname}}.j2
    dest: /etc/dnsmasq.d/pxe.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
  when: pxe_enabled == true

- name: make sure firewalld is running
  service:
    name: firewalld
    enabled: yes
    state: started

- name: configure dnsmasq for DHCP
  block: 
    - name: install dnsmasq.d/dhcp.conf file
      template:
        src: dhcp.conf.{{ansible_hostname}}.j2
        dest: /etc/dnsmasq.d/dhcp.conf
        owner: root
        group: root
        mode: 0644
      notify: restart dnsmasq
  when: dhcp_enabled == true

- name: configure firewall for DHCP # Need this for PXE
  firewalld:
    zone: "{{trusted_firewall_zone}}"
    service: dhcp
    immediate: yes
    state: enabled
    permanent: yes
  notify: restart dnsmasq
  when: dhcp_enabled == true

- name: install /etc/hosts file
  copy:
    src: "hosts.{{ansible_hostname}}"
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq

# This should be in the handler but handlers need to support blocks first
# see https://github.com/ansible/ansible/issues/14270 for details
- name: set selinux context on /etc/dnsmasq.conf and etc/dnsmasq.d
  command: restorecon -RFv {{item}}
  with_items:
    - /etc/dnsmasq.conf 
    - /etc/dnsmasq.d

- name: configure firewall for DNS
  firewalld:
    zone: "{{trusted_firewall_zone}}"
    service: dns
    immediate: yes
    state: enabled
    permanent: yes

- name: configure firewall for PXE
  firewalld:
    zone: "{{trusted_firewall_zone}}"
    port: "{{item}}"
    immediate: yes
    state: enabled
    permanent: yes
  with_items:
    - "68/tcp"
    - "68/udp"
    - "69/tcp"
    - "69/udp"
    - "4011/udp"
  notify: restart dnsmasq
...
