---
- name: install packages
  ansible.builtin.package:
    name: dnsmasq,tftp-server,tftp,httpd,firewalld
    state: latest
  notify: restart dnsmasq

- name: install dnsmasq.conf file
  ansible.builtin.template:
    src: dnsmasq.conf.{{ansible_hostname}}.j2
    dest: /etc/dnsmasq.conf
    owner: dnsmasq
    group: dnsmasq
    mode: 0660
  notify: restart dnsmasq

- name: create /etc/dnsmasq.d directory
  ansible.builtin.file: 
    path: /etc/dnsmasq.d
    owner: dnsmasq
    group: dnsmasq
    mode: 0770
    state: directory
- name: install dnsmasq.d/pxe.conf file
  ansible.builtin.template:
    src: pxe.conf.{{ansible_hostname}}.j2
    dest: /etc/dnsmasq.d/pxe.conf
    owner: dnsmasq
    group: dnsmasq
    mode: 0660
  notify: restart dnsmasq
  when: pxe_enabled == true

- name: make sure firewalld is running
  ansible.builtin.service:
    name: firewalld
    enabled: yes
    state: started

- name: configure dnsmasq for DHCP
  block: 
    - name: install dnsmasq.d/dhcp.conf file
      ansible.builtin.template:
        src: dhcp.conf.{{ansible_hostname}}.j2
        dest: /etc/dnsmasq.d/dhcp.conf
        owner: dnsmasq
        group: dnsmasq
        mode: 0660
      notify: restart dnsmasq
  when: dhcp_enabled == true

- name: configure {{trusted_network_firewall_zone}} firewall zone for DHCP # Need this for PXE
  ansible.builtin.firewalld:
    zone: "{{trusted_network_firewall_zone}}"
    service: dhcp
    immediate: yes
    state: enabled
    permanent: yes
  notify: restart dnsmasq
  when: 
    - dhcp_enabled == true
    - trusted_network_firewall_zone is defined

- name: install /etc/hosts file
  ansible.builtin.copy:
    src: etc.hosts
    dest: /etc/hosts
    owner: dnsmasq
    group: dnsmasq
    mode: 0664
  notify: restart dnsmasq

# This should be in the handler but handlers need to support blocks first
# see https://github.com/ansible/ansible/issues/14270 for details
- name: restore selinux context on /etc/dnsmasq.conf and etc/dnsmasq.d
  ansible.builtin.command: restorecon -RFv {{item}}
  with_items:
    - /etc/dnsmasq.conf 
    - /etc/dnsmasq.d

- name: configure firewall for DNS
  ansible.builtin.firewalld:
    zone: "{{trusted_network_firewall_zone}}"
    service: dns
    immediate: yes
    state: enabled
    permanent: yes
  when: trusted_network_firewall_zone is defined

- name: configure firewall for PXE
  ansible.builtin.firewalld:
    zone: "{{trusted_network_firewall_zone}}"
    port: "{{item}}"
    immediate: yes
    state: enabled
    permanent: yes
  with_items:
    - "69/tcp"
    - "69/udp"
    - "4011/udp"
  when: trusted_network_firewall_zone is defined
  notify: restart dnsmasq
...
