---
- name: install rsync-daemon
  package:
    name: rsync-daemon,firewalld
    state: latest

- name: setup rsync.conf file
  template:
    src: rsync.conf.j2
    dest: /etc/rsyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsync-daemon

- name: start and enable rsync-daemon
  service:
    name: rsyncd
    state: started
    enabled: yes

- name: make sure firewalld is running and enabled
  service:
    name: firewalld
    state: started
    enabled: yes

- name: open firewall ports for rsyncd
  firewalld:
    zone: "{{trusted_firewall_zone}}"
    service: rsyncd
    immediate: yes
    state: enabled
    permanent: yes

...
