---
- name: configure system to keep only 2 most recent kernels
  ansible.builtin.replace:
    path: /etc/dnf/dnf.conf
    regexp: '^installonly_limit=.+\n'
    replace: 'installonly_limit="{{installed_kernel_limit}}"\n'
    owner: root
    group: root
    mode: '0644'
  when: (ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version'] >= "28") or
        (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] >= "8")

