---
- name: setup ifcfg-{{public_firewall_interface}}
  ansible.builtin.template:
    src: "ifcfg-public.j2"
    dest: /etc/sysconfig/network-scripts/ifcfg-{{public_firewall_interface}}
    owner: root
    group: root
    mode: 0644
  notify: restart Network

- name: setup ifcfg-{{trusted_firewall_interface}}
  ansible.builtin.template:
    src: "ifcfg-trusted.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{trusted_firewall_interface}}"
    owner: root
    group: root
    mode: 0644
  notify: restart Network

- name: add {{trusted_firewall_interface}} to {{trusted_firewall_zone}}
  ansible.builtin.firewalld:
    zone: "{{trusted_firewall_zone}}"
    interface: "{{trusted_firewall_interface}}"
    permanent: yes
    state: enabled

- name: add {{public_firewall_interface}} to {{public_firewall_zone}}
  ansible.builtin.firewalld:
    zone: "{{public_firewall_zone}}"
    interface: "{{public_firewall_interface}}"
    permanent: yes
    state: enabled

- name: Set ip forwarding and reload if necessary
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: setup masquerade 
  ansible.builtin.firewalld:
    masquerade: "yes"
    state: enabled
    permanent: yes
    zone: "{{ public_firewall_zone }}"

- name: block firewall ports for unwanted services on {{public_firewall_zone}} zone
  ansible.builtin.firewalld:
    service: "{{item}}"
    state: disabled
    permanent: yes
    zone: "{{ public_firewall_zone }}"
  with_items:
    - cockpit
    - dhcpv6-client
  notify: restart firewalld

- name: enable firewall for sshd on {{public_firewall_zone}} zone
  ansible.builtin.firewalld:
    service: ssh
    state: enabled
    permanent: yes
    zone: "{{ public_firewall_zone }}"
  when: enable_public_sshd|bool 
  notify: restart firewalld

- name: disable firewall for sshd on {{public_firewall_zone}} zone
  ansible.builtin.firewalld:
    service: ssh
    state: disabled
    permanent: yes
    zone: "{{ public_firewall_zone }}"
  when: not enable_public_sshd|bool
  notify: restart firewalld

- name: open firewall for sshd on {{trusted_firewall_zone}} zone
  ansible.builtin.firewalld:
    service: ssh
    state: enabled
    permanent: yes
    zone: "{{ trusted_firewall_zone }}"
