---
- name: add {{trusted_network_interface}} to {{trusted_network_firewall_zone}} zone
  ansible.builtin.firewalld:
    zone: "{{trusted_network_firewall_zone}}"
    interface: "{{trusted_network_interface}}"
    permanent: yes
    state: enabled
    immediate: yes

- name: add {{public_network_interface}} to {{public_network_firewall_zone}} zone
  ansible.builtin.firewalld:
    zone: "{{public_network_firewall_zone}}"
    interface: "{{public_network_interface}}"
    permanent: yes
    state: enabled
    immediate: yes

- name: Set ip forwarding and reload if necessary
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: setup masquerade 
  ansible.builtin.firewalld:
    masquerade: "yes"
    state: enabled
    permanent: yes
    immediate: yes
    zone: "{{ public_network_firewall_zone }}"

