---
- name: Install ProtonVPN Repo
  ansible.builtin.package:
<<<<<<< HEAD
    name: "https://repo.protonvpn.com/fedora-{{ansible_distribution_major_version}}-stable/protonvpn-stable-release-1.0.1-2.noarch.rpm"
=======
    name: "https://repo.protonvpn.com/fedora-39-stable/protonvpn-stable-release/protonvpn-stable-release-1.0.1-2.noarch.rpm"
>>>>>>> c555f7f (Latest Commits)
    state: latest
    disable_gpg_check: yes

#- name: Import a key from a url
#  ansible.builtin.rpm_key:
#    state: present
#    key: http://apt.sw.be/RPM-GPG-KEY.dag.txt

- name: Install ProtonVPN Packages
  ansible.builtin.package:
    name: "{{item}}"
    state: latest
  with_items:
    - libappindicator-gtk3
    - gnome-tweaks
    - gnome-extensions-app
    - gnome-shell-extension-appindicator
    - protonvpn-gui
    - protonvpn-cli

