---
- name: install apcupsd and firewalld packages
  package:
    name: apcupsd,firewalld
    state: latest

- name: setup apcupsd.conf file
  template:
    src: apcupsd.conf.j2
    dest: /etc/apcupsd/apcupsd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apcupsd

- name: restore selinux permissions on /etc/apcupsd
  command: restorecon -RFv /etc/apcupsd

- name: create {{logdir}} directory
  file:
    path: "{{logdir}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: restore selinux permissions on {{logdir}}
  command: restorecon -RFv "{{logdir}}"

- name: start and enable apcupsd
  service:
    name: apcupsd
    state: started
    enabled: yes

- name: make sure firewalld is running and enabled
  service:
    name: firewalld
    state: started
    enabled: yes

- name: open NIS port in Firewall
  firewalld:
    zone: "{{trusted_firewall_zone}}"
    service: apcupsd
    immediate: yes
    state: enabled
    permanent: yes
