---

- name: include smb users data
  include_vars:
    file: samba_users.yml

- name: install samba packages
  ansible.builtin.package:
    name: samba, samba-winbind
    state: latest

- name: set samba SELinux samba_export_all_ro=1 and persistent across reboots
  ansible.builtin.seboolean:
    name: samba_export_all_ro
    state: yes
    persistent: yes

- name: set samba SELinux samba_export_all_rw=1 and persistent across reboots
  ansible.builtin.seboolean:
    name: samba_export_all_rw
    state: yes
    persistent: yes

- name: set samba SELinux samba_enable_home_dirs=1 and persistent across reboots
  ansible.builtin.seboolean:
    name: samba_enable_home_dirs
    state: yes
    persistent: yes

- name: setup smb.conf file
  ansible.builtin.template:
    src: templates/smb.conf.{{ansible_hostname}}.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify: restart samba

- name: setup samba users
  ansible.builtin.shell: (echo '{{ item.passwd }}'; echo '{{ item.passwd }}')
    | smbpasswd -s -a {{ item.name }}
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"
  with_items: "{{ samba_users }}"
  loop_control:
    label: "{{ item.name }}"
  no_log: true

- name: start and enable smb and nmb services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - smb
    - nmb

- name: make sure firewalld is running and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: open trusted firewall zone for samba
  ansible.builtin.firewalld:
    zone: "{{trusted_firewall_zone}}"
    service: samba
    immediate: yes
    state: enabled
    permanent: yes
  when: trusted_firewall_zone is defined

- name: open public firewall zone for samba
  ansible.builtin.firewalld:
    zone: "{{public_firewall_zone}}"
    service: samba
    immediate: yes
    state: enabled
    permanent: yes
  when: offer_public_services == "true"


