---
- name: include sm_creds
  include_vars:
    file: group_vars/sm_creds.yml

- name: Use subscription-manager to Register System RHEL 6/7/8
  ansible.builtin.redhat_subscription:
    state: present
    username: "{{ redhat_portal_username }}"
    password: "{{ redhat_portal_password }}"
    force_register: yes
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version >= "6"

#    pool_ids: "{{ my_pool_ids }}"
