---
- name: fedora.yml - Check to see if {{repoName}}.repo requires backup
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/{{repoName}}.repo"
  register: result

- name: fedora.yml - Backup original {{repoName}}.repo  to /etc/yum.repos.d/save directory
  ansible.builtin.copy:
    src: "/etc/yum.repos.d/{{repoName}}.repo"
    dest: "/etc/yum.repos.d/save/{{repoName}}.repo"
    owner: root
    group: root
    mode: '0644'
    remote_src: true
  when: result.stat.exists
    
- name: fedora.yml - Remove original {{repoName}}.repo from /etc/yum.repos.d
  ansible.builtin.file:
    path: "/etc/yum.repos.d/{{repoName}}.repo"
    state: absent

- name: fedora.yml - Configure {{reponame}}.repo Files to install/update from {{linux_install_server_hostname}}
  template: 
    src: "{{linux_install_server_hostname}}/{{repoName}}-{{linux_install_server_hostname}}.repo.j2"
    dest: "/etc/yum.repos.d/{{repoName}}-{{linux_install_server_hostname}}.repo"
    owner: root
    group: root
    mode: '0644'
...
